---
- name: cleanup
  hosts: all
  become: true
  tasks:
    - name: Cleanup - Delete the converge rule
      puzzle.opnsense.firewall_rules:
        interface: "lan"
        description: "New Test Rule"
        action: pass
        target_port: 100
        state: absent
