---
- name: prepare
  hosts: all
  become: true
  tasks:
    - name: Prepare - Delete the rule to be created
      puzzle.opnsense.firewall_rules:
        interface: "lan"
        description: "New Test Rule"
        action: pass
        target_port: 100
        state: absent

    - name: Prepare - Create the rule to be deleted
      puzzle.opnsense.firewall_rules:
        interface: "lan"
        description: "New Test Rule to Delete"
        action: pass
        target_port: 100
        state: present
