# Copyright: (c) 2023, Reto Kupferschmid <kupferschmid@puzzle.ch>, Puzzle ITC
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

"""Utilities used to apply OPNsense config changes"""

from __future__ import (absolute_import, division, print_function)

__metaclass__ = type

from typing import List
import subprocess

def _run_function(php_requirements: List[str], configure_function: str, configure_params: List = []) -> str:
    """
    Execute a php function optional with parameters

    :param php_requirements: A list os strings containing the location of php files which must be included to execute the function.
    :param configure_function: The php function to call.
    :param configure_params: An optional list of parameters to pass to the function.

    :return: Returns the stdout generated by the command
    """

    # assemble the php require statements
    requirements_string = " ".join(
        ["require '" + req + "';" for req in php_requirements]
    )
    params_string = ",".join(configure_params)

    # assemble php command
    php_cmd = f"{requirements_string} {configure_function}({params_string});"

    # run command
    cmd_result = subprocess.run(
        [
            "php",
            "-r",
            php_cmd,
        ],
        stdout=subprocess.PIPE,
        check=True,  # raise exception if program fails
    )
    return cmd_result.stdout


def system_settings_general() -> List[str]:
    """
    Execute the required php function to apply settings in the System -> Settings -> General (system_general.php) view.
    https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/www/system_general.php#L227

    :return: Returns a list os strings containing the stdout of all the commands executed
    """

    # requirements to execute the various functions can be found in the respective php file
    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/www/system_general.php#L30
    php_requirements = [
        "/usr/local/etc/inc/config.inc",
        "/usr/local/etc/inc/util.inc",
        "/usr/local/etc/inc/system.inc",
        "/usr/local/etc/inc/interfaces.lib.inc",
        "/usr/local/etc/inc/interfaces.inc",
        "/usr/local/etc/inc/filter.inc",
    ]

    cmd_output = []
    # the order of commands executed is relevant
    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/www/system_general.php#L227

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/system.inc#L935
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="system_timezone_configure",
            configure_params=["true"], # first param: verbose
        )
    )

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/system.inc#L864
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="system_trust_configure",
            configure_params=["true"], # first param: verbose
        )
    )

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/system.inc#L864
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="system_hostname_configure",
            configure_params=["true"], # first param: verbose
        )
    )

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/system.inc#L506
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="system_resolver_configure",
            configure_params=["true"], # first param: verbose
        )
    )

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/plugins.inc#L251
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="plugins_configure",
            configure_params=["'dns'", "true"], # first param: hook, second param: verbose
        )
    )

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/plugins.inc#L251
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="plugins_configure",
            configure_params=["'dhcp'", "true"], # first param: hook, second param: verbose
        )
    )

    # https://github.com/opnsense/core/blob/cbaf7cee1f0a6fabd1ec4c752a5d169c402976dc/src/etc/inc/filter.inc#L125
    cmd_output.append(
        _run_function(
            php_requirements=php_requirements,
            configure_function="filter_configure",
            configure_params=["true"], # first param: verbose
        )
    )
    return cmd_output
