---
# tasks file for opnsense_configure

- name: Configure System Settings
  include_tasks:
    file: system_settings.yml
    apply:
      tags:
        - system_settings

- name: Configure Firewall
  include_tasks:
    file: firewall.yml
    apply:
      tags:
        - firewall