---
driver:
  name: vagrant
  parallel: true

platforms:
  - name: "22.7"
    hostname: False
    box: puzzle/opnsense
    box_version: "22.7"
    memory: 1024
    cpus: 2
    instance_raw_config_args:
      - 'vm.guest = :freebsd'
      - 'ssh.sudo_command = "%c"'
      - 'ssh.shell = "/bin/sh"'
  - name: "23.1"
    box: puzzle/opnsense
    hostname: False
    box_version: "23.1"
    memory: 1024
    cpus: 2
    instance_raw_config_args:
      - 'vm.guest = :freebsd'
      - 'ssh.sudo_command = "%c"'
      - 'ssh.shell = "/bin/sh"'

provisioner:
  name: ansible
verifier:
  name: ansible
  options:
    become: true
